[project]
name = "ctsr-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "duckdb>=1.3.1",
    "polars[pyarrow]>=1.31.0",
    "vl-convert-python>=1.8.0",
]
